### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LaansDole**

### CODE REVIEW

**Review by whitemirror1212 — APPROVED** [review]

**Review by s3878707 — APPROVED** [review]

**Review by miketvo — CHANGES_REQUESTED** [review]
Merge this into dev, then merge dev into main, like our usual workflow.

Also finish the instructions for VS Code first.

**Comment by LaansDole** [comment]
> Merge this into dev, then merge dev into main, like our usual workflow.
> 
> Also finish the instructions for VS Code first.

Okay boss, will be done today

**Comment by miketvo** [comment]
Okay boss, will review tonight

**Comment by miketvo** [comment]
Why did we close this? @LaansDole @nguyennguyenkhuong1212 @s3878707

**Comment by miketvo** [comment]
Reopened because of duplication in #19

**Review by LaansDole — COMMENTED** [review]
update readme.md

**Review by miketvo — APPROVED** [review]
LGTM

**Pull request merged**
